version: "3"

networks:
  backend:
  postgres:
  # web:

volumes:
  postgresql-data:

services:
  phoenix:
    image: afonsir/phoenix:1.2.5-alpine
    build: .
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
    volumes:
      - .:/app
    ports:
      - 80:4000
    networks:
      - backend
      - postgres

  postgres:
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - postgres
